[profile.default]
src = "src"
out = "out"
fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'forge-std/=lib/forge-std/src/',
    'murky/=lib/murky/',
    'foundry-devops/=lib/foundry-devops/src/'
]
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
